### ISSUE TITLE
Optimize whitespace with tags section

### ISSUE THREAD

**Issue by anavarre** [sn-extensions/autocomplete-tags#1]
Adding / viewing tags currently works like this:

![apache-tag](https://user-images.githubusercontent.com/293478/28012864-74a84f2e-6567-11e7-83fb-64034779298b.png)

This results in a lot of whitespace being used as a result, especially with the fullscreen view:

![apache-tag-fullscreen](https://user-images.githubusercontent.com/293478/28012863-74a719c4-6567-11e7-9031-b13cf36b0202.png)

I thus suggest optimizing the whitespace usage to adding / viewing tags on the same line. This will also improve the UX a bit.

![whitespace-optimized](https://user-images.githubusercontent.com/293478/28012862-749fa0cc-6567-11e7-82f6-2f3fb8ae3bbb.png)

**Comment by ryanpcmcquen** [comment]
@mobitar & @anavarre, I agree completely! This extension is great but really hurts the UX with how much real estate it takes. Especially on smaller screens. Should just be some simple HTML & CSS changes to fix this.
![screenshot 1516816934](https://user-images.githubusercontent.com/772937/35348759-defab502-00ed-11e8-97be-6b61fff73223.png)

The main part is shortening the height of `#note-tags-component-container`. Then decreasing the width of the two fields and making them `float: left;`.

**Comment by mobitar** [comment]
Good point. Forgot about this. I'm revisiting all the extensions and this might be a good time to rethink this.

**Comment by ryanpcmcquen** [comment]
This hasn't actually changed though ... as far as I can tell.

**Comment by mobitar** [comment]
On Desktop, click Extensions, then update this ext. On web, refresh the page.

**Comment by ryanpcmcquen** [comment]
I have refreshed on web ...

**Comment by mobitar** [comment]
Clear cache? Working for me..

<img width="633" alt="screen shot 2018-02-28 at 4 39 17 pm" src="https://user-images.githubusercontent.com/3277844/36817213-f6190b98-1ca5-11e8-8deb-798076fd1816.png">

**Comment by mobitar** [comment]
Also make sure you're installing from the Extensions window via the new format. To be safe, just uninstall it, then reinstall it.

**Comment by ryanpcmcquen** [comment]
Cleared all site data in the dev tools, then I uninstalled and reinstalled Autocomplete tags ... it still looks like this:
![screenshot 1519857795](https://user-images.githubusercontent.com/772937/36817355-b7b928ca-1c95-11e8-8540-019a4fd94b5d.png)

**Comment by mobitar** [comment]
If you were apart of the beta of 2.1, you might be using the old extended code, and not receiving updates.

Extensions -> Options (next to Repository) -> Delete.

Then go to dashboard.standardnotes.org, and find your new Extended code.

**Comment by ryanpcmcquen** [comment]
I will try that.

**Comment by ryanpcmcquen** [comment]
That did not work either.

**Comment by mobitar** [comment]
Can you try a different browser?

On Feb 28, 2018, at 4:59 PM, Ryan P. C. McQuen <notifications@github.com>
wrote:

That did not work either.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/sn-extensions/autocomplete-tags/issues/1#issuecomment-369413581>,
or mute the thread

**Comment by ryanpcmcquen** [comment]
I'm on Chrome, I can try Firefox at home.

**Comment by ryanpcmcquen** [comment]
@anavarre, is it working for you?

**Comment by mobitar** [comment]
I just ran into this on Chrome, and the solution was to open the Developer Console, then press and hold on the Refresh button and click Empty Cache and Hard Reload.

<img width="341" alt="screen shot 2018-02-28 at 8 24 07 pm" src="https://user-images.githubusercontent.com/3277844/36823946-64d2918e-1cc5-11e8-933f-25c2ca34cfa3.png">
