### ISSUE TITLE
The dropdown that shows "tags to add" should put non-nested first

### ISSUE THREAD

**Issue by hlascelles** [sn-extensions/autocomplete-tags#19]
Given this example:

![2021-05-26_13-10](https://user-images.githubusercontent.com/299102/119659353-fba69d80-be25-11eb-8a76-93396c263d5c.png)

I would like the unnested one (in this case, `work`) would come first so I could just hit "down and enter".

I could have a go at a PR if you agree?

Also, does this repo have / need tests?

**Comment by atmoio** [comment]
We'll be phasing out this extension soon in favor of a native component that does the same thing. But you're still definitely welcome to submit a PR if you'd like to have this functionality sooner. No tests in this repo.

**Comment by hlascelles** [comment]
Aha... If it's included in the rewrite I will wait for that. Looking forward to it, thanks!
