### ISSUE TITLE
Adding subfolder tags will add parent tag as well

### ISSUE THREAD

**Issue by christianhans** [sn-extensions/autocomplete-tags#6]
Let's say I have a tag #parent.sub contained as subfolder in #parent.

When I use the autocomplete component to assign the tag #parent.sub to my note it will also assign the tag #parent to my note.

I can see why some people would want to do that, but I personally always remove the added parent tag. I guess by adding parent tags someone would be able to find all notes in subfolders. This however gets messy when parent tags are accidentally removed from notes. I rather use Smart Tags to list all notes within a specific folder.

I suggest to change this behavior and not add parent tags when assigning a sub tag to a note.

**Comment by mobitar** [comment]
(Same thread here: https://github.com/sn-extensions/folders-component/issues/17)

**Comment by alandooz** [comment]
As a duplicated issue maybe it can be closed as it contains less information than the mentioned thread.
